# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rdb_reader
  pool: 5
  username: rdb_reader
  password: Z0R3oSzzNpoovK7i5
  socket: /var/lib/mysql/mysql.sock
